#!/bin/bash
# iterative-conditioning 0.0.1
# Generated by dx-app-wizard.
#
# Basic execution pattern: Your app will run on a single machine from
# beginning to end.
#
# Your job's input variables (if any) will be loaded as environment
# variables before this script runs.  Any array inputs will be loaded
# as bash arrays.
#
# Any code outside of main() (or any entry point you may add) is
# ALWAYS executed, followed by running the entry point itself.
#
# See https://documentation.dnanexus.com/developer for tutorials on how
# to modify this file.

main() {

    echo "Value of ANNOTATION_DIR: '${ANNOTATION_DIR[@]}'"
    echo "Value of LOCO_DIR: '${LOCO_DIR[@]}'"
    echo "Value of KEEP: '$KEEP'"
    echo "Value of PHENOTYPES: '$PHENOTYPES'"
    echo "Value of COVARIATES: '$COVARIATES'"
    echo "Value of PLINK_BIM: '$PLINK_BIM'"
    echo "Value of PLINK_BED: '$PLINK_BED'"
    echo "Value of PLINK_FAM: '$PLINK_FAM'"
    echo "Value of GENE_TRAIT_PAIRS_TO_TEST: '$GENE_TRAIT_PAIRS_TO_TEST'"

    # Organise all of the directories
    dx-download-all-inputs --parallel

    KEEP_PATH=$(find /home/dnanexus/in/KEEP -type f)
    PHENOTYPES_PATH=$(find /home/dnanexus/in/PHENOTYPES -type f)
    COVARIATES_PATH=$(find /home/dnanexus/in/COVARIATES -type f)
    GENE_TRAIT_PAIRS_PATH=$(find /home/dnanexus/in/GENE_TRAIT_PAIRS_TO_TEST -type f)
    
    echo "Keep: $KEEP_PATH"
    echo "Phenotypes: $PHENOTYPES_PATH"
    echo "Covariates: $COVARIATES_PATH"
    echo "Gene-trait pairs: $GENE_TRAIT_PAIRS_PATH"

    mkdir in/annotation in/loco in/keep in/phenotypes in/covariates

    mv ${KEEP_PATH} in/keep/
    mv ${PHENOTYPES_PATH} in/phenotypes
    mv ${COVARIATES_PATH} in/covariates
    mv in/LOCO_DIR/*/* in/loco
    mv in/ANNOTATION_DIR/*/* in/annotation

    rm -r in/ANNOTATION_DIR in/LOCO_DIR in/KEEP in/PHENOTYPES in/COVARIATES

    # Tidy up the run_files and saige_outputs directories so that they match as expected
    mkdir -p in/run_files/bed
    mkdir -p in/regenie_outputs

    if ls in/phenotypes/*.gz 1> /dev/null 2>&1; then
        gunzip in/phenotypes/*.gz
    else
        echo "No gz files found."
    fi

    if ls in/covariates/*.gz 1> /dev/null 2>&1; then
        gunzip in/covariates/*.gz
    else
        echo "No gz files found."
    fi

    # Find their name
    PHENOTYPES_PATH=$(find in/phenotypes -type f)
    COVARIATES_PATH=$(find in/covariates -type f)

    # First job is to move all files to expected paths, so that I can run the snakemake
    git clone --branch main --depth 1 https://github.com/astheeggeggs/common_condition.git
    
    # Move the data inside
    DATA_DIR="snakemake_${ANC}"

    # PLINK
    PLINK_BIM_IN_DIR="/home/dnanexus/in/PLINK_BIM"
    PLINK_BED_IN_DIR="/home/dnanexus/in/PLINK_BED"
    PLINK_FAM_IN_DIR="/home/dnanexus/in/PLINK_FAM"

    if [[ -d "$PLINK_BIM_IN_DIR" && -d "$PLINK_BED_IN_DIR" && -d "$PLINK_FAM_IN_DIR" ]]; then
        echo "plink directories exists, finding files..."
        PLINK_BIM_PATH=$(find "$PLINK_BIM_IN_DIR" -type f)
        PLINK_BED_PATH=$(find "$PLINK_BED_IN_DIR" -type f)
        PLINK_FAM_PATH=$(find "$PLINK_FAM_IN_DIR" -type f)
        if [[ -n "$PLINK_BIM_PATH" && -n "$PLINK_BED_PATH" && -n "$PLINK_FAM_PATH" ]]; then
            PLINK_DIR="in/plink"
            mkdir -p "$PLINK_DIR"
            mv "$PLINK_BIM_PATH" "$PLINK_DIR"/
            mv "$PLINK_BED_PATH" "$PLINK_DIR"/
            mv "$PLINK_FAM_PATH" "$PLINK_DIR"/
        fi
    else
        echo "One or more PLINK files missing, skipping."
    fi

    mv ${GENE_TRAIT_PAIRS_PATH} common_condition/
    mkdir common_condition/${DATA_DIR}
    mv in/* common_condition/${DATA_DIR}/

    docker pull astheeggeggs/brava-common-check-regenie:latest
    docker run \
      -v $(pwd)/common_condition:/common_condition \
      -w /common_condition \
      --env ANC=${ANC} \
      --env CHR=chr${CHR} \
      --env P_T=${P_T} \
      --env DATA_DIR=snakemake_${ANC} \
      astheeggeggs/brava-common-check-regenie:latest \
      bash /common_condition/run_step1_iterative_conditioning_regenie_uk-biobank_dnanexus_applet.sh
    
    mkdir -p ~/out/run_files/chr${CHR} ~/out/regenie_outputs/chr${CHR} ~/out/combined_outputs

    mv common_condition/*.log ~/out/run_files/chr${CHR}/
    mv common_condition/logs ~/out/run_files/chr${CHR}/
    mv common_condition/run_files/* ~/out/run_files/chr${CHR}/
    mv common_condition/regenie_outputs/* ~/out/regenie_outputs/chr${CHR}/
    mv common_condition/brava_stepwise_conditional_analysis_regenie_results.txt ~/out/combined_outputs/brava_${ANC}_chr${CHR}_stepwise_conditional_analysis_regenie_results.txt
    # mv common_condition/brava_stepwise_conditional_analysis_results.txt.singleAssoc.txt ~/out/combined_outputs/brava_${ANC}_chr${CHR}_stepwise_conditional_analysis_results.txt.singleAssoc.txt
    mv common_condition/brava_stepwise_conditional_analysis_regenie_results.txt.conditioning.variants.txt ~/out/combined_outputs/brava_${ANC}_chr${CHR}_stepwise_conditional_analysis_regenie_results.txt.conditioning.variants.txt

    dx-upload-all-outputs --parallel
}
