#!/bin/bash
# iterative-conditioning 0.0.1
# Generated by dx-app-wizard.
#
# Basic execution pattern: Your app will run on a single machine from
# beginning to end.
#
# Your job's input variables (if any) will be loaded as environment
# variables before this script runs.  Any array inputs will be loaded
# as bash arrays.
#
# Any code outside of main() (or any entry point you may add) is
# ALWAYS executed, followed by running the entry point itself.
#
# See https://documentation.dnanexus.com/developer for tutorials on how
# to modify this file.

main() {

    echo "Value of MODEL_DIR: '${MODEL_DIR[@]}'"
    echo "Value of SPARSE_MATRIX: '${SPARSE_MATRIX}'"
    echo "Value of SPARSE_MATRIX_IDs: '${SPARSE_MATRIX_IDs}'"
    echo "Value of VARIANCE_DIR: '${VARIANCE_DIR[@]}'"
    echo "Value of GROUP_DIR: '${GROUP_DIR[@]}'"
    echo "Value of VCF: '$VCF'"
    echo "Value of VCF_CSI: '$VCF_CSI'"
    echo "Value of PLINK_BIM: '$PLINK_BIM'"
    echo "Value of PLINK_BED: '$PLINK_BED'"
    echo "Value of PLINK_FAM: '$PLINK_FAM'"
    echo "Value of GENE_TRAIT_PAIRS_TO_TEST: '$GENE_TRAIT_PAIRS_TO_TEST'"

    # Organise all of the directories
    dx-download-all-inputs --parallel

    SPARSE_MATRIX_PATH=$(find /home/dnanexus/in/SPARSE_MATRIX -type f)
    SPARSE_MATRIX_IDS_PATH=$(find /home/dnanexus/in/SPARSE_MATRIX_IDs -type f)
    GENE_TRAIT_PAIRS_PATH=$(find /home/dnanexus/in/GENE_TRAIT_PAIRS_TO_TEST -type f)
    
    echo "Sparse matrix: $SPARSE_MATRIX_PATH"
    echo "Sparse matrix IDs: $SPARSE_MATRIX_IDS_PATH"
    echo "Gene-trait pairs: $GENE_TRAIT_PAIRS_PATH"

    mkdir in/model in/variance in/groupfile in/mtx

    mv ${SPARSE_MATRIX_PATH} in/mtx/
    mv ${SPARSE_MATRIX_IDS_PATH} in/mtx/
    mv in/MODEL_DIR/*/* in/model
    mv in/VARIANCE_DIR/*/* in/variance
    mv in/GROUP_DIR/*/* in/groupfile

    rm -r in/MODEL_DIR in/VARIANCE_DIR in/GROUP_DIR in/SPARSE_MATRIX in/SPARSE_MATRIX_IDs

    # Tidy up the run_files and saige_outputs directories so that they match as expected
    if [ -d "in/RUN_DIR" ]; then
        mv "in/RUN_DIR/*/*" in/RUN_DIR/
        mkdir in/RUN_DIR/bed
        mv in/RUN_DIR/*bed in/RUN_DIR/bed/
        mv in/RUN_DIR in/run_files
    else
        mkdir in/run_files
    fi

    if [ -d "in/SAIGE_DIR" ]; then
        mv "in/SAIGE_DIR/*/*" in/SAIGE_DIR/
        mv in/SAIGE_DIR in/saige_outputs
    else
        mkdir in/saige_outputs
    fi

    # First job is to move all files to expected paths, so that I can run the snakemake
    git clone --branch main --depth 1 https://github.com/astheeggeggs/common_condition.git
    
    # Move the data inside
    DATA_DIR="snakemake_${ANC}"

    # VCF
    VCF_IN_DIR="/home/dnanexus/in/VCF"
    VCF_CSI_IN_DIR="/home/dnanexus/in/VCF_CSI"

    if [[ -d "$VCF_IN_DIR" && -d "$VCF_CSI_IN_DIR" ]]; then
        echo "vcf directories exists, finding files..."
        VCF_PATH=$(find "$VCF_IN_DIR" -type f)
        VCF_CSI_PATH=$(find "$VCF_CSI_IN_DIR" -type f)
        if [[ -n "$VCF_PATH" && -n "$VCF_CSI_PATH" ]]; then
            VCF_DIR="in/vcf/combined"
            mkdir -p "$VCF_DIR"
            mv "$VCF_PATH" "$VCF_DIR"/
            mv "$VCF_CSI_PATH" "$VCF_DIR"/
        fi
    else
        echo "VCF and/or VCF_CSI file missing, skipping."
    fi

    # PLINK
    PLINK_BIM_IN_DIR="/home/dnanexus/in/PLINK_BIM"
    PLINK_BED_IN_DIR="/home/dnanexus/in/PLINK_BED"
    PLINK_FAM_IN_DIR="/home/dnanexus/in/PLINK_FAM"

    if [[ -d "$PLINK_BIM_IN_DIR" && -d "$PLINK_BED_IN_DIR" && -d "$PLINK_FAM_IN_DIR" ]]; then
        echo "plink directories exists, finding files..."
        PLINK_BIM_PATH=$(find "$PLINK_BIM_IN_DIR" -type f)
        PLINK_BED_PATH=$(find "$PLINK_BED_IN_DIR" -type f)
        PLINK_FAM_PATH=$(find "$PLINK_FAM_IN_DIR" -type f)
        if [[ -n "$PLINK_BIM_PATH" && -n "$PLINK_BED_PATH" && -n "$PLINK_FAM_PATH" ]]; then
            PLINK_DIR="in/plink"
            mkdir -p "$PLINK_DIR"
            mv "$PLINK_BIM_PATH" "$PLINK_DIR"/
            mv "$PLINK_BED_PATH" "$PLINK_DIR"/
            mv "$PLINK_FAM_PATH" "$PLINK_DIR"/
        fi
    else
        echo "One or more PLINK files missing, skipping."
    fi

    mv ${GENE_TRAIT_PAIRS_PATH} common_condition/
    mkdir common_condition/${DATA_DIR}
    mv in/* common_condition/${DATA_DIR}/

    docker pull gcr.io/weighty-elf-452116-c7/brava-common-check:v4
    docker run \
      -v $(pwd)/common_condition:/common_condition \
      -w /common_condition \
      --env ANC=${ANC} \
      --env CHR=chr${CHR} \
      --env DATA_DIR=snakemake_${ANC} \
      gcr.io/weighty-elf-452116-c7/brava-common-check:v4 \
      bash /common_condition/run_step1_iterative_conditioning_uk-biobank_dnanexus_applet.sh
    
    mkdir -p ~/out/run_files/chr${CHR} ~/out/saige_outputs/chr${CHR} ~/out/combined_outputs

    mv common_condition/*.log ~/out/run_files/chr${CHR}/
    mv common_condition/logs ~/out/run_files/chr${CHR}/
    mv common_condition/run_files/* ~/out/run_files/chr${CHR}/
    mv common_condition/saige_outputs/* ~/out/saige_outputs/chr${CHR}/
    mv common_condition/brava_stepwise_conditional_analysis_results.txt ~/out/combined_outputs/brava_${ANC}_chr${CHR}_stepwise_conditional_analysis_results.txt
    mv common_condition/brava_stepwise_conditional_analysis_results.txt.singleAssoc.txt ~/out/combined_outputs/brava_${ANC}_chr${CHR}_stepwise_conditional_analysis_results.txt.singleAssoc.txt
    mv common_condition/brava_stepwise_conditional_analysis_results.txt.conditioning.variants.txt ~/out/combined_outputs/brava_${ANC}_chr${CHR}_stepwise_conditional_analysis_results.txt.conditioning.variants.txt

    dx-upload-all-outputs --parallel
}
